source/README
source/core/3rd_party_licenses/3RD_PARTY_LICENSES

We decided about a different handling of 3rd party licenses. A list can now be found at OXIDforge, the PDF in core/ is obsolete.

removed core/3rd_party_licenses/, corrected typos in README, added a link

---

source/core/oxinputvalidator.php

The function checkCountries in oxinputvalidator sets the validation error to the field oxpassword. But that is the wrong field. It has to be oxcountryid.

Bugfix: wrong validation error field in checkCountries

---

source/application/views/admin/tpl/discount_main.tpl

Add an block to add the possibility to extend the discount item table without overwriting whole template

add block to admin/discount_main.tpl

---

source/application/views/azure/tpl/widget/reviews/reviews.tpl

To allow user write a review without login you need to assign the hash earlyer in Template and check it like oxcmp_user.

Write review without login with userhash

---

.travis.yml
tests/Library/test_config.inc.php
tests/Library/test_utils.php
tests/bootstrap.php
tests/unit/OxidTestCase.php
tests/unit/core/oxemailAzureTplTest.php
tests/unit/core/oxnewsTest.php

When looking through previous pull requests you may notice that very few of them ship with unittests. I think one reason for this is the lack of configuration documentation about the environment you need to successfully execute the whole OXID eShop testsuite and another reason may be the effort you need to invest to configure the required software stack (with PHP version matrix) including all dependencies.
I'm aware of the repository tomasliubinas/vagrant-oxideshop but this requires the contributor to install a bunch of additional software packages besides the fact that the chef recipes don't work with current versions of chef and Sebastian Bergmann did shutdown the corresponding pear channel. Testsuite execution over different versions of PHP is also not possible with this solution.
I'm …

add full functional Travis CI configuration

---

source/application/controllers/admin/genexport_do.php

What sense does it make to first replace all line break chars with newline and then output everything with additional carriage return + newline? we should either simply stick to the newline we chose before or make this configurable.

Update genexport_do.php, fix mixed line endings on export

---

source/application/controllers/admin/navigation.php
source/application/views/admin/de/lang.php
source/application/views/admin/en/lang.php
source/application/views/admin/tpl/shop_performance.tpl

We have 17 languages and 32 shops in our Shop. If we login to admin panel, the admin checks the collations on nearly every klick. This makes a high workload for the backend and the backend is very sluggish.
I think it would be a good idea to add a configurable checkbox in performance settings for systemrequirement check in dashboard.

Adding checkbox for configurable performance check in dashboard

---

source/application/views/admin/tpl/tooltips.tpl

`getOffset` returns both `top` and `left` coordinates, thus invoking it twize is unnecessary

Cache `getOffset` invokation

---

source/Core/oxutilsserver.php

this fix method isCurrentUrl so it can recognize the current url if the request goes directly to an php file in a module (that may call the oxid bootstrap by it self)
this is a blocker for me, because some modules already do handle requests directly by there self, and the bootstrap will get the wrong shop id in some situations.

this fix method isCurrentUrl (for modules that handle request directly)

---

source/Core/ViewHelper/JavaScriptRenderer.php

backslash must also be escaped, because the javascript may already include the escape character
(not yet tested, just ported from an recent fix from oxps async javascript module)

backslash must also be escaped in javascript

---

source/Application/Model/oxarticle.php
source/Core/Base.php
source/Core/oxutilsdate.php
tests/unit/core/I18nTest.php
tests/unit/core/oxbaseTest.php
tests/unit/models/oxactionlistTest.php
tests/unit/models/oxarticleTest.php
tests/unit/models/oxdiscountlistTest.php
tests/unit/models/oxsearchTest.php

by replacing the current time with a rounded request time it's possible for the query cache to hit the an cached sql query.
I used a 1 minutes interval for rounding so all queries can be cached(hit) for at least 1 minutes,
I did no performance test on this, would be great to get some feedback if it helps.
To test the "active from/to" stetting must be enabled, and you need high load situations on specific category pages.

performance can be improved by using intervalls and REQUEST_TIME

---

source/Application/Model/oxarticle.php
source/Application/Model/oxcategory.php

when using load or assign method on the same object again the seourl you will get the wrong seo url.
pseudo code:
```
$obj = oxNew('oxArticle')
$obj->load('123');
print $obj->getLink(); # e.g. http://myshop/123.html
$obj->load('3');
print $obj->getLink(); # again http://myshop/123.html because first time the url is cached. 
#the correct output should be something like http://myshop/3.html
```

clear internally cached seourl in oxarticle and oxcategory

---

source/Application/views/admin/tpl/navigation.tpl
source/Application/views/admin/tpl/order_overview.tpl
source/Application/views/admin/tpl/user_main.tpl
source/out/admin/src/main.css

In the order overview in the backend the name of the user and the customer number got a link, so you can jump from the order directly to the user (better usability). It is possible to install more links (for the articles for example) so you have more cross references and it is easier to navigate.

admin change: link from order to user for a better usability

---

source/Setup/tpl/_header.php

The `/>` syntax is not allowed for void elements in HTML4. We should be using HTML5 anyway by now.

Fix invalid HTML in setup by upgrading Doctype to HTML5

---

.travis.yml

see https://docs.travis-ci.com/user/languages/php#Disabling-preinstalled-PHP-extensions and https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer
> Compared to a cli command run with "xdebug" enabled a speed improvement by a factor of up to 3 is not uncommon.

Disable xdebug for travis build

---

source/Application/Model/oxuser.php

oxInputValidator->checkEmail only has 2 parameters (from which one is not even used), here 3 parameters were given

bugfix: wrong parameter count used for checkEMail

---

source/Application/Controller/BaseController.php
tests/Unit/Application/Controller/UBaseTest.php

set the language attribute in html is even if performance option to load languages is not enabled.
To do so i use the shop internal language abbr, that should be avail without loading the setting from the database,
so we will still have performance benefit but without loosing functionality to set html language
(in most cases, in special if internal language abbr matches the ISO 639-1 language abbr).

set html language regardless of performance settings

---

README.md

[According to Rachel Berry](https://lwn.net/Articles/688542/), a GitHub representative, contact information should be included in a project's README file, especially if the GitHub issue tracker is disabled (which should seldomly be done)

Include contact information in README

---

source/Application/Controller/Admin/DiscountArticlesAjax.php
source/Application/Controller/Admin/DiscountItemAjax.php
tests/Unit/Application/Controller/Admin/DiscountArticlesAjaxTest.php
tests/Unit/Application/Controller/Admin/DiscountItemAjaxTest.php

https://bugs.oxid-esales.com/view.php?id=6027

6027 - Added a further SQL query part to check if the parent is buyable.

---

source/Application/Model/User.php

According to the documentation `User::getSelectedAddress` will return the id of the selected user address. This is not true since not the address identification but the hole address object will be returned.
Fixed documentation to reflect behaviour.

Fix User::getSelectedAddress documentation

---

source/Core/PictureHandler.php
tests/Unit/Core/PictureHandlerTest.php

https://bugs.oxid-esales.com/view.php?id=5720

5720 - Use the method Utils::checkUrlEndingSlash instead of a hard coded slash

---

source/Application/Controller/BaseController.php
tests/Unit/Application/Controller/UBaseTest.php

[Fixed bug 6083](https://bugs.oxid-esales.com/view.php?id=6083) 
- Added a check if the given sort field name is existing
- Replaced deprecated calls in BaseController::getUserSelectedSorting
- Wrote tests.

6083 - article sorting fields not verified against valid field from admin settings

---

source/Application/Model/Payment.php
tests/Unit/Application/Model/OrderTest.php

Problem are the following lines:
`$dPrice = $this->getPaymentValue($this->getBaseBasketPriceForPaymentCostCalc($oBasket));`
`if ($dPrice) {`
`...`
If there is no price it does nothing. This is no problem for the first order. But if you change it from a payment type which costs money to zero it will not remove it because of the if-statement. I added an else to explicitly set the costs to 0 if there are none.
https://bugs.oxid-esales.com/view.php?id=6398

0006398: Payment type charges are not deleted changed back to a type with no costs

---

source/Application/views/admin/tpl/discount_list.tpl

Html entity should/must be followed by an ;
http://stackoverflow.com/questions/18689230/why-do-html-entity-names-with-dec-255-not-require-semicolon

add semicolon to html entity

---

source/Application/views/admin/tpl/content_main.tpl

Der invalide HTML führt dazu, dass es zu fehlern beim Speichern kommt, wenn Module den Block verwenden. Das Problem besteht ebenfalls bei allen anderen TEmplates im BE!

Fixed invalid html

---

source/Application/Component/Widget/oxwcategorytree.php
source/Application/views/azure/tpl/widget/header/categorylist.tpl
source/Application/views/azure/tpl/widget/sidebar/categorytree.tpl

Category created from CMS Pages do not show the Selection as other categories. The fix will also change how the category gets displayed in the sidebar.

Background for selected CMS Page categories in Navigation and in the Category tree

---

source/config.inc.php.dist

iDebug can be set -1, then the shop is more strict about missing templates and other errors.

better documentation for "-1" value for debuglevel

---

source/Core/UtilsObject.php

This is a minor improvement of the internal object creation process, 
that will help to simplify things by making it possible to use oxNew direcly or indirectly within the oxNew function.
technically: Set the not overloaded(by modules) version of UtilsObject as instance before creating the overloaded version.
- also some littel removement of duplicate code 
- some comments

enable to use oxNew during utilsobject bootstrap

---

source/Core/Utils.php
tests/Unit/Application/Controller/CmpShopTest.php
tests/Unit/Core/UtilsTest.php

the benefit of not redirecting is:
- clear status code for the caller (500) so the client knows about the error
- http standard: using 500 status with body instead of 500 with location header 
- enable the client to resend the request by refreshing the page (helps to fix the problem, can help to restore data)
- enable the client to navigate back in history

show offlinepage directly instead of redirects

---

source/Core/Language.php
tests/Unit/Core/LangTest.php

Language files without the `charset` key are not included, e.g.
```php
<?php
$sLangName = "English";
$aLang = [
'KEY' => 'value',
];
```

load language files even without 'charset' key

---

source/Application/views/admin/tpl/admin_links.tpl
source/Application/views/admin/tpl/admin_news.tpl
source/Application/views/admin/tpl/article.tpl
source/Application/views/admin/tpl/category.tpl
source/Application/views/admin/tpl/content.tpl
source/Application/views/admin/tpl/include/frameset.tpl
source/Application/views/admin/tpl/order.tpl
source/Application/views/admin/tpl/selectlist.tpl

Removing duplicate code because it is the root of all evil.
- extracted duplicate code into an other template and included that.
- removes about 80% code from the affected files.
- it could be done better by using only one template at all, but i suggest refactoring on template level with 'include' statements first because you can use that pattern almost everywhere without any BC breaks and with low efforts.

remove copypaste frameset in admin area

---

source/Core/UtilsObject.php

To generate an oxid (ox-id) we are using the PHP function md5. This function returns always a string with a length of 32 chars. Because of the good ol' days the md5 function is wrapped with substr, which cuts the returned string of the md5 function to 32 chars. This isn't necessary anymore.

Remove substr from oxid generation

---

.gitignore

About error, in category list wrong category was selected. This was because parent category ID was '003' and other category ID was '03'. And then '==' comparison tries to compare these strings, it interprets them like a numbers. Fixed by strcmp() which checks strings in binary level.

Category tree, selected category search fix

---

source/Application/Controller/Admin/DiscountArticlesAjax.php
tests/Unit/Application/Controller/Admin/DiscountArticlesAjaxTest.php

Please see https://bugs.oxid-esales.com/view.php?id=6501#c11770 for more information, especially 
> Reporter in 0006027 says it is wrong that you can assign an unbuyable item as a discount. He does not say it is wrong to assign an unbuyable parent to a discount. It is a good thing if unbuyable parents can be assigned, just as you can assign categories, which are also not buyable.

removed changes from PR390 therefore unbuyable parents can be assigned again.

---

source/Application/Model/RssFeed.php

Added space after from-prices
"was: from28.90"
changed to
"from 28.90"
all glory goes to @dassaffe (aka Daniel Fuhs)

Added space

---

source/Application/Controller/BaseController.php

btw. getRequestUrl is deprecated, and it has some magic (it checks if it is a post request), which should be better done by the caller

removed unused parameters in method call

---

source/Application/Controller/BaseController.php

if you somehow call the internal url (not the seo url) on (for example) a category,
the redirect to the seo optimized url will not use 301.
This similar to:
https://bugs.oxid-esales.com/view.php?id=5471
but may occur only in special situation because normally the non seo urls are not used in links.

use 301 code for permanent redirects

---

source/Core/Utils.php

fix failing php7.1 build
see also #518 and eb6af3562e60095c48f3267a1a9fb4b72cb36490
btw: We use `(float)` and `(double)` in the code. Maybe we should use just one of these?

cast value to float

---

source/config.inc.php.dist

I did a few things here with the background that the file is basically a file which represents a part of class attributes from \OxidEsales\EshopCommunity\Core\Config.
1. Normalized the comments. 
- A comment which needs only one line is beginning with two Slashes and a whitespace.
- Multiple line comments have the comment pattern of a method comment.
2. Fixed typos.
3. Added or removed line breaks.
What is missing and will not be added are the public / protected / private keywords for the class attributes as this could have to much impact.

normalized the comments, fixed some typos.

---

source/Application/Model/User.php
tests/Unit/Application/Model/UserTest.php

There is a case when User::delete method returns null. Unnecessary code is written.
Deleted this code.

Fix User::delete

---

tests/Integration/Modules/BaseModuleInheritanceTestCase.php
tests/Integration/Modules/BaseModuleTestCase.php
tests/Integration/Modules/ModuleActivateWithSimilarNameTest.php

Let autoloader do the trick.
Require_once for BaseModuleTestCase in ModuleActivateWithSimilarNameTest breaks vendor/bin/runtests in vm.

Remove unneeded require_once statements in module tests

---

source/Application/Model/Category.php
tests/Unit/Application/Model/CategoryTest.php

Remove questenmark from externel links
Discussed in oxid developer skype chat and found the same issue described in german oxid forum
http://forum.oxid-esales.com/showthread.php?t=12884
bug https://bugs.oxid-esales.com/view.php?id=6498

Remove questenmark from external link

---

source/Core/UtilsObject.php

As OXID eShop requires PHP 5.6 and higher, it is possible to use arguments unpacking.

Use argument unpacking instead of Utilsobject::_getObject

---

source/Application/Model/Basket.php

if `$sId` is set, `getCosts()` will return an `oxPrice` object, otherwise it will be an array with all costs

fix wrong return type in docblock

---

source/Application/Model/Voucher.php
source/Core/Language.php
source/Core/Module/ModuleInstaller.php

* There is no particular difference between intval and typecast (int) 
* [typecast is faster](http://stackoverflow.com/questions/1912599/is-there-any-particular-difference-between-intval-and-casting-to-int-int-x#comment39379007_1912613)
---
Related to source/Application/Model/Voucher.php:
You can omit the first value after the ternary operator to use the second value as a fallback. ([see here](http://stackoverflow.com/a/5972529/2123108))
```
Psy Shell v0.7.2 (PHP 7.0.15-0ubuntu0.16.04.4 — cli) by Justin Hileman
>>> $a = '2';
=> "2"
>>> (int) $a ?: 3;
=> 2
>>>
```

replace intval with typecast

---

source/Application/Component/UserComponent.php

allowing minibasket and menu on privatesales login page so the login page so it can have the same layout then other pages.
The mini basket will of cause be empty, but it enables to reuse template structure by including the default page layout within the private sales login page:
```
[{include file="layout/page.tpl"}]
```
without this PR, developers will end up in infinitive loops because the privatesales check will cause a redirect to the login page, because the widgets included on that login page will redirect again to the loginpage.
This only a quick workaround for this bug, but i guess it will cover more then 90% of the use cases where no other widgets (with access to the user component) are used within the normal layout.

allowing minibasket on privatesales login page

---

source/Core/Edition/EditionRootPathProvider.php
source/Setup/Utilities.php
source/Setup/functions.php

`VENDOR_PATH` [has already](https://github.com/OXID-eSales/oxideshop_ce/blob/68d569564cede01b839da8e56ae9390e349214be/source/bootstrap.php#L32) a `DIRECTORY_SEPARATOR` at the end:
```
define('VENDOR_PATH', INSTALLATION_ROOT_PATH . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR);
```

remove duplicate directory separator

---

source/Core/StrMb.php

The `StrMb` Class wraps some php functions like `preg_match`. Some of these functions are not in camelCase. phpcs reports this as an error, so I wrapped that in an ignore block (via `@codingStandardsIgnoreStart` and `@codingStandardsIgnoreEnd`)

ignore StrMb-wrapper functions (phpcs)

---

source/Application/views/admin/de/lang.php

added german translation for 'GENERAL_ARTICLE_OXVARMAXPRICE'

GENERAL_ARTICLE_OXVARMAXPRICE missing.

---

source/Core/Email.php

This is a property in the `Email` class, which extends the `PHPMailer` class (class.phpmailer.php).
The property `SMTP_PORT` is used only in the `SMTP` class (class.smtp.php)
```
$ grep -rI 'SMTP_PORT' .
./vendor/phpmailer/phpmailer/class.smtp.php:    const DEFAULT_SMTP_PORT = 25;
./vendor/phpmailer/phpmailer/class.smtp.php:     * @deprecated This is only ever used as a default value, so use the `DEFAULT_SMTP_PORT` constant instead
./vendor/phpmailer/phpmailer/class.smtp.php:     * @see SMTP::DEFAULT_SMTP_PORT
./vendor/phpmailer/phpmailer/class.smtp.php:    public $SMTP_PORT = 25;
./vendor/phpmailer/phpmailer/class.smtp.php:            $port = self::DEFAULT_SMTP_PORT;
```

rename $SMTP_PORT to $smtpPort

---

source/Core/UtilsServer.php

this avoid setting cookies in CLI, because a lot of console scripts suffer from warnings "headers already sent" because oxLang creates a cookie.

do not try to set cookies in CLI

---

source/Core/UtilsFile.php

while UtilsFile::processFiles/processFile  with parameter $blUseMasterImage = true
the shop cannot create a subfolder on demand.
f.e. the master/product/* folders doesn't exist (after installation of oxid v6.0.0.0) you cant use the method with blMasterImage = true; 
you get a warning: 
Warning: copy(/.../oxideshop_ce/source/out/pictures/master/product/1/kitefix_self-adhesive_dacron_1.jpeg): failed to open stream: No such file or directory in /.../oxideshop_ce/source/Core/UtilsFile.php on line 376

added mkdir if folders not exist in _copyFile method

---

source/Core/SeoEncoder.php

The Parameter $iShopId didn't get passed along to the call to _loadFromDb() which results in null being returned if you try to retrieve a static url from another subshop like so:
oxRegistry::get("oxSeoEncoder")->getStaticUrl("index.php?cl=account_order", $iLang, $iShopId);
If $iShopId is not the same as the active shop, you get null returned.

pass along shopid to call to _loadFromDb()

---

source/robots.txt

https://bugs.oxid-esales.com/view.php?id=6703
Fixed the "robots.txt is case sensitive" bug and updated the path of the english terms and conditions site.

fix for b6703

---

source/Application/Model/SeoEncoderArticle.php

Replace every occurrence of `.html` with call to `$this->_getUrlExtension()`

Cleanup url extension in SeoUrlEncoderArticle

---

source/Application/Controller/FrontendController.php

If an registered user is logged in without UStID, the FrontendController returns the wrong value for VAT included.
This is due to a type mismatch in PHP.
The if statement has a explicit type comparison to null, the given value from the database is an empty string ''. (Line: 2952 | Application/Controller/FrontendController.php)
Mantis #6902 (https://bugs.oxid-esales.com/view.php?id=6902)

Wrong return value FrontendController.isVatIncluded()

---

source/Application/views/admin/tpl/inc_error.tpl

Warning: count(): Parameter must be an array or an object that implements Countable in /source/tmp/smarty/9f82ed8fbbbe090e6a26df004c8d6113^%%47^47B^47B0D5FE%%inc_error.tpl.php on line 4
See screenshot.

Fix: Run-time warning in inc_error.tpl

---

source/Application/Model/Article.php
tests/Unit/Application/Model/ArticleTest.php

Hi there,
in `\OxidEsales\EshopCommunity\Application\Model\Article` the method `getDeliveryDate` returns the date on which the specified article will be on stock again, aka restocked.
The word _delivery_ in the shop is always used from the customers point of view, not the merchants one, so I propose we change the wording from _delivery_ to _restock_ to be consistent.
This pull request:
- deprecates the `getDeliveryDate()` method
- adds the `getRestockDate()` method
/Flo

Deprecate misleading method Article::getDeliveryDate()

---

source/Core/Registry.php
source/oxfunctions.php

Using the variable return type declaration fixes PHPstan warnings when scanning my modules

return type of oxNew is the classname given

---

CHANGELOG.md
source/Application/views/admin/tpl/shop_main.tpl

because this prevents the browser to fill in wrong data in empty fields and that prevents antecedently wrong smtp configuration or personal passwords to be stored in that field.
That fields are used to be empty in environments where a local mail forwarder is installed.

turning off autocomplete for smtp fields

---

.gitignore

Its 
`/var/generated/generated_services.yaml`
not
`/var/generated_services.yaml`

fix for generated_services in gitignore

---

source/Application/Model/Newsletter.php
source/Core/UtilsView.php

I just got this error while working in a project:
```
ERROR: InvalidArgument - extensions/oxps/newslettersending/Core/NewsletterProcessor.php:93:42 - Argument 1 of OxidEsales\Eshop\Application\Model\Newsletter::prepare expects string, object provided (see https://psalm.dev/004)
$newsletter->prepare($user, $loadAction);
```

Fix wrong type for user parameter in Newsletter

---

source/Core/Language.php

There is a special case in the language class, when `translateString` returns an `array` (for `_aSeoReplaceChars`).
A better solution would be to refactor the code so that this always returns a string.

Fix wrong return type in language class

---

source/Application/translations/de/lang.php
source/Application/translations/en/lang.php

The shop requires a translation corresponding to the key 'PAGE_TITLE_START'. This has already been mentioned in a comment from 23 August 2018 here: https://github.com/OXID-eSales/oxideshop_ce/pull/520. 
To see that this is indeed the case you can for instance set a break point in the `getTitle()` method in the `FrontendController` and refresh the shop's start page. 
https://github.com/OXID-eSales/oxideshop_ce/blob/b-6.2.x/source/Application/Controller/FrontendController.php#L1893

Add missing translation

---

source/Core/SimpleXml.php
tests/Unit/Core/SimpleXmlTest.php

addChild() in SimpleXml.php does not escape some special chars and objectToXml() will generate broken XML.
If for example a value with a '&'-character would appear in the value of an object it would not get escaped to &amp; and the resulting XML will be invalid (->asXml() will actually also generate a php warning)
More information about this issue: https://stackoverflow.com/a/555039 / https://bugs.php.net/bug.php?id=45253

SimpleXml / objectToXml() does not escape special characters like & correctly

---

source/admin/oxajax.php

Shows up as code smell in sonarcloud in OXID cloud projects

Remove redundant return statement

---

source/Application/translations/de/cust_lang.php.dist
source/Application/translations/en/cust_lang.php.dist

Added empty and prepared cust_lang.php.dist files to the translations directory for de and en: As a shop user I want so see prepared and ready-to-use files for my language alterations. In support and forums, this way it is much easier to explain how to maintain one's own translations and stay updatable.

added empty cust_lang.php.dist files for de and en

---

source/.htaccess

We need to make sure that grapqhl controller is always calles with skipSession=true. Rewrite rule in shop's .htaccess will enforce this.

OXDEV-4221 Update rewrite rule for graphql to always skip the session

---

source/Application/views/admin/tpl/user_main.tpl

the "new password" field in user management triggers browser autofill function and might overwrite the password of selected user if you do not clean this field manually.
Adding `autocomplete="new-password"` to this field will prevent browser's autofill function

prevent password autofill

---

source/Application/Controller/BasketController.php
source/Application/Model/Basket.php
tests/Integration/Price/VouchersForSpecificCategoriesAndProductsAndUserGroupsTest.php
tests/Unit/Application/Model/BasketTest.php

Currently the addVoucher method in the basket model is passing errors directly to the display. This contradicts the MVC pattern and should be handled by the basket controller. This PR fixes that issue.

Fix mvc pattern add voucher

---

source/Application/Model/Voucher.php

When reusing times out vouchers, prefer those with the longest timeout.

OXDEV-4430 Improve voucher recycling

---

CHANGELOG.md
source/Core/Autoload/UnifiedNameSpaceClassMap.php
source/Core/Exception/LanguageNotFoundException.php
source/Core/Language.php
source/Core/ViewConfig.php
tests/Unit/Core/ConfigTest.php
tests/Unit/Core/LangTest.php
tests/Unit/Core/Module/ModuleTest.php

I stumbled upon [this issue](https://gist.github.com/alfredbez/e03e3797d2cf73c40969b8fa452ea76a) a few times and finally took some time to think about a better fix, than just to fail with a weird error message.
Things to cleanup if you like the idea:

Throw exception if language could not be loaded

---

CHANGELOG.md
source/Core/Module/ModuleChainsGenerator.php

in rare case a module overloads \OxidEsales\Eshop\Core\Module\Module and gets for example deleted 
then the shops must not try to call oxNew for \OxidEsales\Eshop\Core\Module\Module because that would create a endless loop.
this kind of loops can result very hard to debug segmentation fault (because out of memory errors in combination with xdebug)
My first try to fix this was not sufficient, anyway it looks like this regression is only in oxid eShop 6.2 but not before, at least I did not hit it in oxid 6.1

fix endless loop on module error

---

bin/oe-console

oe-console needs the eventdispatcher, otherwise we won't be able to extend console commands by additional parameters like shop-id for EE.

Add EventDispatcher

---

source/Application/Model/ActionList.php

Fixed typo in SQL statement in ActionList.php. 
Previously this SQL query would throw fatal error:
`Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'oxtypex' in 'where clause' `

Fix typo in ActionList.php

---

source/Internal/Framework/Module/Setting/SettingDao.php
tests/Unit/Internal/Framework/Module/ShopModuleSetting/SettingDaoTest.php

As the [documentation](https://docs.oxid-esales.com/developer/en/6.2/development/tell_me_about/event/ModuleEvents/SettingChangedEvent.html) says, the event should be triggered when the module settings change. Therefore I expect the event also when I change module settings in admin.

Missing Event SettingChanged

---

source/Application/Controller/ArticleDetailsController.php
tests/Unit/Application/Controller/DetailsTest.php

To date, status 200 was output when an SEO existed for an article. But the article is no longer present in the DB.
With this SQL a URL is created for a non exits article OXID.
```sql
INSERT INTO `oxseo` (`OXOBJECTID`, `OXIDENT`, `OXSHOPID`, `OXLANG`, `OXSTDURL`, `OXSEOURL`, `OXTYPE`, `OXFIXED`, `OXEXPIRED`, `OXPARAMS`, `OXTIMESTAMP`)
VALUES
('b56369b1fc9d7b97f9c5fc343b349ece', 'b2e64c19290bff182ed2947ec51f0349', 1, 0, 'index.php?cl=details&amp;anid=ANY_OXID_FOR_ARTICLE', 'Kiteboarding/Kites/Kite-CORE-GTS-OXID-IS-WRONG.html', 'oxarticle', 0, 0, '0f4fb00809cec9aa0910aa9c8fe36751', '2021-06-14 12:48:48');
```
with `http://oxiddemo.local/Kiteboarding/Kites/Kite-CORE-GTS-OXID-IS-WRONG.html` should come status 404 not 200.
or simple
http://oxiddemo.local/index.php?cl=details&anid=notexistingprod …

404 Page at a SEO Url where the oxarticels__oxid is no longer present.

---

CHANGELOG.md
source/Core/Model/BaseModel.php

We need something like that for GraphQL to get unencoded data,
otherwise we will end up with html encoded titles, descriptions etc. which will cause trouble with frontends.
Decision for GraphQL was to use getFieldData instead of old magic getters to have one clear central point to fetch data from. So if we introduce a solution like getRawFieldData method directly in shop (6.3.x if we have another release, otherwise 6.4.x) we have all we need in one method.

OXDEV-4888 Add method BaseModel::getRawFieldData to get unencoded values

---

CHANGELOG.md
source/Application/Model/Article.php
tests/Unit/Application/Model/ArticleTest.php

Hey there :vulcan_salute: 
the return value of the `OxidEsales\EshopCommunity\Application\Model\Article::getCategory` method is not easy to work with and puts a burden on the caller. This PR tries to fix most of it.
- you might get `null` or `\OxidEsales\Eshop\Application\Model\Category`
- but `\OxidEsales\Eshop\Application\Model\Category` is not guaranteed to be initialized
Therefore the caller musst always check if the returned value is `null` and if not, call the `getId()` method and check that response additionally to make sure.
Return type is still `Category|null` but with this patches applied, you can not get an uninitialized Category object anymore.
- wrong usage of static member `_aCategoryCache` with `$this` instead of `self`
- you can not rely on the `Category::isLoaded()` …

Fix return value for Article::getCategory method

---

source/Application/Controller/Admin/LoginController.php

There is no possibility to throw your own error messages in the admin login area as the message is hard coded.
When adding new functionality to the admin login, it may be necessary to show own messages instead of the "Wrong Username/Password",

Allows to throw own exception messages in admin login

---

source/Core/Email.php

The Email class is often extended with own send methods for additional email functionality. To adapt the core principals of the logic from this class it is crucial to have access to the getRenderer method in extended classes, otherwise it needs to be reemplemented every single time.

Change access to getRenderer method in Email class

---

source/Application/Controller/Admin/VoucherSerieMain.php

If nothing or something different than an integer or a float was provided, the shop will throw an exception:
```
OXID Logger.ERROR: abs(): Argument #1 ($num) must be of type int|float, string given ["[object] (TypeError(code: 0): abs(): Argument #1 ($num) must be of type int|float, string given at /var/www/oxideshop/vendor/oxid-esales/oxideshop-ce/source/Application/Controller/Admin/VoucherSerieMain.php:102)\n[stacktrace]\n#0 /var/www/oxideshop/vendor/oxid-esales/oxideshop-ce/source/Application/Controller/Admin/VoucherSerieMain.php(102): abs('')\n#1 /var/www/oxideshop/vendor/oxid-esales/oxideshop-ce/source/Core/Controller/BaseController.php(534): OxidEsales\\EshopCommunity\\Application\\Controller\\Admin\\VoucherSerieMain->save()\n#2 …
```

Cast the discount value to float to prevent an exception

---

CHANGELOG.md
source/Application/Controller/Admin/VoucherSerieMain.php
source/Core/OnlineVatIdCheck.php

Why?
- missing handling for service response errors
What did we do?
- add error cases that lead to a new request

extend handling for service response errors
