OXID-eSales/oxideshop_ce

- CONTRIBUTING.md
- README.md
adding CLAHub service to this repository, cleaned up language, removed text for issues
> adding CLAHub service to this repository

- source/core/oxemail.php
remove undefined variable to avoid warning
> remove undefined variable

- source/application/views/admin/tpl/order_main.tpl
add blocks to order_main.tpl to extend only parts of this page and avoid overwriting the whole template
> add blocks to admin/order_main.tpl

- source/application/models/oxdiscountlist.php
fix some doc blocks and add comments for better IDE completion
> fix some doc blocks

- source/application/views/admin/de/help_lang.php
- source/application/views/admin/de/lang.php
NAVIGATION_SYSREQ_MESSAGE_INACTIVE,
SHOP_PERF_SYSREQ_CHECK, HELP_SHOP_PERF_SYSREQ_CHECK
> Adapted lang keys for fitting PR #209

- source/application/views/admin/tpl/header.tpl
- source/application/views/admin/tpl/home.tpl
> new blocks in application/views/admin/tpl/header.tpl and home.tpl

- source/application/models/oxbasket.php
Add some type hints to foreach loops for better IDE Completion
> add some type hints

- source/application/views/azure/tpl/widget/product/listitem_grid.tpl
For further information see https://bugs.oxid-esales.com/view.php?id=6059
> 0006059: strong-tag not closed in listitem_grid.tpl when in b2b mode

- source/application/views/admin/tpl/tooltips.tpl
For further information see https://bugs.oxid-esales.com/view.php?id=6061
> 0006061: tooltip position calculation doesn't consider window width

- source/application/controllers/admin/user_list.php
- tests/unit/admin/userlistTest.php
For further information see https://bugs.oxid-esales.com/view.php?id=6060
> 0006060: user list is not up-to-date when deleting a user from list

- source/application/models/oxvoucher.php
fix discout typo in method names
> fix typos in method names

- source/application/models/oxvoucher.php
> fix return type in doc block

- source/application/views/admin/de/lang.php
hopefully this should show less changes this time... seems GitHub does not react very nicely to non-UTF8 encoded files...
> fixed wrong translation of "role" to "Recht"

- source/Application/views/admin/tpl/pagenavisnippet.tpl
It would be nice for modules if we got a block here =)
> Added Smarty Block to pagenavisnippet

- source/modules/oe/invoicepdf/models/invoicepdfoxorder.php
changes for Ticket 5936
http://bugs.oxid-esales.com/view.php?id=5936
> Not possible to override InvoicePdf module class InvoicepdfArticleSummary

- source/offline.html
- shop shop logo
- auto reload after 10 seconds
- maintenance message
- noindex/nofollow
> improve offline.html

- source/Core/Database/Doctrine.php
- source/Core/LegacyDatabase.php
- tests/integration/core/Database/Adapter/DoctrineResultSetTest.php
- tests/integration/core/Database/DatabaseInterfaceImplementationBaseTest.php
- tests/integration/core/Database/DatabaseInterfaceImplementationTest.php
- tests/integration/core/Database/DoctrineTest.php
- tests/integration/core/Database/LegacyDatabaseTest.php
- tests/unit/core/Database/DoctrineTest.php
Split test into a general test, which test the DatabaseInterfaceImplementation and a test for each Implementation (Doctrine and LegacyDatabase)
> ESDEV-3493 Refactored tests

- source/Application/Component/Widget/oxwarticledetails.php
- source/Application/Controller/ArticleDetailsController.php
- source/Application/Model/oxarticle.php
- tests/Unit/Application/Component/Widget/ArticleDetailsTest.php
- tests/Unit/Application/Controller/DetailsTest.php
fixes: https://bugs.oxid-esales.com/view.php?id=6368
> fixed DocBlock and changed return type to boolean

- source/Core/oxutilsserver.php
if shop runs in https only mode we can set secure flag to all cookies
> secure cookies

- source/Core/oxwidgetcontrol.php
Removed duplicate code in classname is oxubase, the only diff. left is the setClassName call.
> try to simplify view chain code

- source/Core/oxmoduleinstaller.php
> use $sModuleId instead of $oModule->getId()

- source/Application/Model/oxuser.php
As I understand that comment, this @todo is already done, isn't it?
> remove @todo that was already done

- source/Core/Config.php
- tests/Unit/Core/ConfigTest.php
Add a method to check if the shop runs only in https mode
> method to check https only mode

- source/Setup/En/lang.php
typo fixes by @NHWS:
[http://forum.oxid-esales.com/showthread.php?t=39527#post179604](http://forum.oxid-esales.com/showthread.php?t=39527#post179604)
> typo fixes

- source/Application/Model/Category.php
- tests/Unit/Application/Model/CategoryTest.php
https://bugs.oxid-esales.com/view.php?id=6030
> 6030 - The flag isLoaded is not set to true when to object is loaded successfully.

- source/Core/WidgetControl.php
Remove all parent views added to the chain
> Fix view chain

- source/Application/Model/Order.php
return ( double ) ... obviously returns double, not int
> change wrong returntype for getOrderSum in docstring

- source/Application/Controller/BaseController.php
- tests/Unit/Application/Controller/UBaseTest.php
https://bugs.oxid-esales.com/view.php?id=5384
> 5384: When a country has the option "Do not bill VAT", the shop shows "* incl. VAT, plus shipping" anyway

- source/Application/Controller/Admin/PaymentMain.php
- tests/Unit/Application/Controller/Admin/PaymentMainTest.php
https://bugs.oxid-esales.com/view.php?id=6450
> 6450: Creation of empty fields in payments

- source/Application/Model/User.php
remove unused variables & parameters, fixed some typos
> cleanup User-Model

- source/Application/views/admin/tpl/article_attribute.tpl
- source/Application/views/admin/tpl/article_crossselling.tpl
- source/Application/views/admin/tpl/article_files.tpl
- source/Application/views/admin/tpl/article_overview.tpl
- source/Application/views/admin/tpl/attribute_category.tpl
- source/Application/views/admin/tpl/attribute_main.tpl
- source/Application/views/admin/tpl/category_order.tpl
- source/Application/views/admin/tpl/delivery_main.tpl
- source/Application/views/admin/tpl/deliveryset_main.tpl
- source/Application/views/admin/tpl/discount_main.tpl
- source/Application/views/admin/tpl/include/category_main_form.tpl
- source/Application/views/admin/tpl/login.tpl
- source/Application/views/admin/tpl/navigation.tpl
- source/Application/views/admin/tpl/navigation_shopselect.tpl
- source/Application/views/admin/tpl/news_main.tpl
- source/Application/views/admin/tpl/order_main.tpl
- source/Application/views/admin/tpl/payment_main.tpl
- source/Application/views/admin/tpl/usergroup_main.tpl
- source/Application/views/admin/tpl/vendor_main.tpl
- source/Application/views/admin/tpl/wrapping_main.tpl
Add more blocks to several admin templates.
> Alpha sys add more admin blocks

- source/application/views/admin/tpl/order_downloads.tpl
> closing </form> tag missed

- source/Core/Edition/EditionRootPathProvider.php
- source/Core/InputValidator.php
- source/Core/Language.php
- source/Core/Module/ModuleTemplatePathCalculator.php
- source/Core/ModuleInstaller.php
- source/Core/ModuleList.php
- source/Core/OnlineCaller.php
- source/Core/Output.php
- source/Core/PictureHandler.php
- source/Core/Price.php
- source/Core/PriceList.php
- source/Core/Request.php
- source/Core/SeoEncoder.php
- source/Core/SepaIBANValidator.php
- source/Core/Session.php
- source/Core/ShopControl.php
- source/Core/StandardList.php
- source/Core/StrMb.php
- source/Core/StrRegular.php
- source/Core/SuperConfig.php
- source/Core/SystemRequirements.php
- source/Core/Utils.php
- source/Core/UtilsDate.php
- source/Core/UtilsObject.php
- source/Core/UtilsUrl.php
- source/Core/UtilsView.php
- source/Core/ViewConfig.php
- source/Core/WidgetControl.php
diff without whitespace changes: https://github.com/OXID-eSales/oxideshop_ce/pull/494/files?w=1
> Code sniffer check passed successfully! Errors count is 569, threshold is set to 659.
> fixed some phpcs errors

- source/Core/DynamicImageGenerator.php
> cyclomatic complexity improvements

- source/Application/Model/Basket.php
Fix the Invalid argument supplied for foreach() warning.
> Fix php warning

- source/Application/views/admin/tpl/module_list.tpl
I need a new block in the modules list page.
This will allow us to create a module, which will filter the modules displayed on this page.
Thanks in advance
> New block in admin, containing the table with the modules list

- source/Application/Model/Basket.php
PriceList@calculateToPrice [checks already](https://github.com/OXID-eSales/oxideshop_ce/blob/162c687e67f7b20017d0b6694a4ad850b054cbe6/source/Core/PriceList.php#L204-L205) if there are any items
> fixup basket wrapping calculation

- source/Application/views/admin/tpl/login.tpl
- source/out/admin/src/login.css
It's better to have the style information in its own place and it has the neat effect, that the CSS code from the admin login page can finally be cached by the browser.
> Catched wild CSS code from the template and put it into an own CSS file.

- source/Core/Sha512Hasher.php
I replaced `$sString` with `$string`.
> apply PSR-2 style rules to Sha512Hasher.php

- source/Application/views/admin/en/lang.php
Translation (even english) missing for GENERAL_ARTICLE_OXVARMAXPRICE
> Language file: GENERAL_ARTICLE_OXVARMAXPRICE

- README.md
There should be no angle-bracket in the URL.
> IDE-Helper-URL adjusted

- source/application/controllers/account.php
before using it in ELSE statement
> Declare var. outide the IF branch before using it in ELSE statement

- source/Core/Session.php
Removing some unused variables in Session
> cleaning up unused variables

- source/Internal/Framework/Module/Configuration/Dao/ModuleConfigurationDao.php
remove not needed `BasicContext` dependency
> Remove not needed dependency from code

- source/Core/Database/Adapter/Doctrine/Database.php
- source/Core/DatabaseProvider.php
- source/config.inc.php.dist
- tests/Integration/Core/Database/Adapter/Doctrine/DatabaseTest.php
Started at https://github.com/OXID-eSales/oxideshop_ce/pull/753
> Database driver options config

- source/Core/Field.php
I updated the setter within Fields.php
We didn't change to overall logic. But we gained some minor performance improvement while getting a big readability improvement.
@flow-control was kind enough to make some perfomance checks
**Before update**
`
benchValueFromField.......I0 [μ Mo]/r: 8.280 8.280 (μs) [μSD μRSD]/r: 0.000μs 0.00%
benchRawValueFromField.....I0 [μ Mo]/r: 1.955 1.955 (μs) [μSD μRSD]/r: 0.000μs 0.00%
benchValueFromRawField.....I0 [μ Mo]/r: 2.026 2.026 (μs) [μSD μRSD]/r: 0.000μs 0.00%
benchRawValueFromRawField..I0 [μ Mo]/r: 2.564 2.564 (μs) [μSD μRSD]/r: 0.000μs 0.00%
`
**After changes**
`
benchValueFromField.......I0 [μ Mo]/r: 7.714 7.714 (μs) [μSD μRSD]/r: 0.000μs 0.00%
benchRawValueFromField.....I0 [μ Mo]/r: 1.961 1.961 (μs) [μSD μRSD]/r: 0.000μs 0.00% …
> Update field to improve performance

- tests/Codeception/acceptance.suite.yml
- tests/Codeception/acceptanceAdmin.suite.yml
- tests/Codeception/config/params.php
Hi there :raised_hands:
this pull request makes selenium host configurable so it works with the https://github.com/OXID-eSales/docker-eshop-sdk without any local changes anymore.
/Flo
> Make selenium host configurable

- source/Internal/Framework/Module/Install/Service/BootstrapModuleInstaller.php
Follow-up action for closed PR https://github.com/OXID-eSales/oxideshop_ce/pull/797
Bug track: https://bugs.oxid-esales.com/view.php?id=7137
Commits moved to b-6.2.x branch from master
> fix possible bug https://bugs.oxid-esales.com/view.php?id=7137 (#2)

- source/Core/Model/BaseModel.php
- Instead of iterating "if" statements, using fixed value
> Performance enhancement

- source/admin/oxajax.php
Shows up as code smell in sonarcloud if OXID cloud projects
> remove commented out code

- source/Application/Component/BasketComponent.php
- source/Application/Controller/Admin/OrderMain.php
improve readability of some array declarations
> minor: array code-style

- source/Application/Model/OrderArticle.php
Hi there,
I just found this wrong docblock, wanted to submit this quickly before leaving OXID.
:cry: This might be my last PR, cu all :wave:
> Fix wrong docblock in OrderArticle

- source/Application/Controller/Admin/NavigationController.php
by proposal of @keywan-ghadami-oxid
> use https to check for new version

- source/Application/Controller/OrderController.php
- source/Application/Model/Basket.php
- source/Application/Model/Order.php
- source/Application/Model/Voucher.php
- tests/Unit/Application/Model/OrderTest.php
This PR improves voucher handling. CI tests are ok but fyim so far no new tests 
have been added.
> OXDEV-4430 Improve voucher handling

- source/Application/Model/Remark.php
https://bugs.oxid-esales.com/view.php?id=7217
> Save Remarks loses oxcreate date

- CHANGELOG.md
- source/Application/Controller/OrderController.php
return type must include null because it multiple places do return without return without value
> Fix return type in phpdoc
